services:
  mqtt:
    image: emqx/emqx:5.8.0
    container_name: horixonst-mqtt
    restart: unless-stopped
    environment:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_DASHBOARD__DEFAULT_USERNAME: mqtt
      EMQX_DASHBOARD__DEFAULT_PASSWORD: "20025@BLELoRa"
      EMQX_AUTH__USER__1__USERNAME: mqtt@user
      EMQX_AUTH__USER__1__PASSWORD: "20025@BLELoRa"
      EMQX_DASHBOARD__LISTENER__HTTP__ENABLE: "true"
      EMQX_DASHBOARD__LISTENER__HTTP__BIND: 0.0.0.0:18083
    ports:
      - "127.0.0.1:1883:1883"
      - "127.0.0.1:8883:8883"
      - "127.0.0.1:8083:8083"
      - "127.0.0.1:8084:8084"
      - "127.0.0.1:18083:18083"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
      - emqx-config:/opt/emqx/etc

  db:
    image: postgres:15-alpine
    container_name: horixonst-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: horixonst
      POSTGRES_USER: Horizonst_user
      POSTGRES_PASSWORD: 20025@BLELoRa
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - horixonst-data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/00-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Horizonst_user -d horixonst"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  pgadmin:
    image: dpage/pgadmin4:8.13
    container_name: horixonst-pgadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@horizonst.com.es}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin1234}
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT:-80}
      SCRIPT_NAME: ${PGADMIN_SCRIPT_NAME:-/pgadmin}
      PGADMIN_PREFERRED_URL_SCHEME: ${PGADMIN_PREFERRED_URL_SCHEME:-https}
      GUNICORN_TIMEOUT: ${PGADMIN_GUNICORN_TIMEOUT:-120}
    ports:
      - "127.0.0.1:${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin/config_local.py:/pgadmin4/config_local.py:ro
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/login"]
      interval: 10s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: horixonst-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      mqtt:
        condition: service_started
    environment:
      PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: Horizonst_user
      DB_PASSWORD: 20025@BLELoRa
      DB_NAME: horixonst
      DB_ROOT_USER: Horizonst_user
      DB_ROOT_PASSWORD: 20025@BLELoRa
      DB_ROOT_DATABASE: postgres
      DB_BOOTSTRAP_SCHEMA: ${DB_BOOTSTRAP_SCHEMA:-on-create}
      DB_SCHEMA_PATH: ${DB_SCHEMA_PATH:-}
      MQTT_HOST: ${MQTT_HOST:-mqtt}
      MQTT_PORT: ${MQTT_PORT:-1883}
      MQTT_USER: ${MQTT_USER:-mqtt@user}
      MQTT_PASS: ${MQTT_PASS:-20025@BLELoRa}
      MQTT_CLIENT_PREFIX: ${MQTT_CLIENT_PREFIX:-acces_control_server_}
      MQTT_KEEPALIVE: ${MQTT_KEEPALIVE:-60}
      MQTT_RECONNECT_PERIOD: ${MQTT_RECONNECT_PERIOD:-1000}
      MQTT_PROTOCOL_ID: ${MQTT_PROTOCOL_ID:-}
      MQTT_PROTOCOL_VERSION: ${MQTT_PROTOCOL_VERSION:-4}
      MQTT_CLEAN: ${MQTT_CLEAN:-true}
      MQTT_ENCODING: ${MQTT_ENCODING:-utf8}
      MQTT_CONNECT_TIMEOUT: ${MQTT_CONNECT_TIMEOUT:-10000}
      JWT_SECRET: ${JWT_SECRET:-supersecretjwtkey}
      HTTPS_ENABLED: ${HTTPS_ENABLED:-false}
      HTTPS_CERT_PATH: ${HTTPS_CERT_PATH:-/certs/app-8080.crt}
      HTTPS_KEY_PATH: ${HTTPS_KEY_PATH:-/certs/app-8080.key}
    ports:
      - "127.0.0.1:8080:8080"
volumes:
  horixonst-data:
  pgadmin-data:
  emqx-data:
  emqx-log:
  emqx-config:
