# Custom pgAdmin configuration for reverse proxy under /pgadmin/
# Generated by automation to ensure compatibility with Nginx path-based routing.
#
# Setting SCRIPT_NAME ensures that all links generados por pgAdmin respetan el
# subpath /pgadmin mientras la aplicación sigue escuchando en el puerto 80 sin
# TLS dentro del contenedor.

import os

SCRIPT_NAME = os.getenv("SCRIPT_NAME", "/pgadmin")
PREFERRED_URL_SCHEME = os.getenv("PGADMIN_PREFERRED_URL_SCHEME", "https")
ENABLE_PROXY_FIX = True
