# Custom pgAdmin configuration for reverse proxy under /pgadmin/
# Generated by automation to ensure compatibility with Nginx path-based routing.
#
# By setting SCRIPT_NAME and URL_PREFIX we ensure that all links generated by
# pgAdmin include the /pgadmin prefix while keeping the application listening
# on the default port 80 without TLS.

import os

SCRIPT_NAME = '/pgadmin'
URL_PREFIX = '/pgadmin'
PREFERRED_URL_SCHEME = os.getenv('PGADMIN_PREFERRED_URL_SCHEME', 'https')
SECURITY_HEADERS = {
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
}

# Allow pgAdmin to trust the proxy headers from Nginx
USE_X_HEADERS = True
